# Flatten43tb Right Shield Configuration

CONFIG_ZMK_KEYBOARD_NAME="Flatten43tb"

# NFC pins as GPIOs
CONFIG_NFCT_PINS_AS_GPIOS=y

# Pointing / Mouse
CONFIG_ZMK_POINTING=y
CONFIG_ZMK_MOUSE=y

# PMW3610 Trackball
CONFIG_PMW3610=y
CONFIG_PMW3610_RUN_DOWNSHIFT_TIME_MS=3264
CONFIG_PMW3610_REST1_SAMPLE_TIME_MS=20

# Battery reporting
CONFIG_ZMK_BATTERY_REPORTING=y

# RGB LED Widget disabled
CONFIG_RGBLED_WIDGET=n
